"""CodeMind Analyzer — root cause analysis and fix blueprint generation.

Bridges the gap between "GAIA detected a problem" (Samvega, immune, observer)
and "GAIA knows how to fix it" (CodeMind PROPOSE stage).

For simple issues (lint, single-file), returns a direct fix target.
For complex issues (behavioral bugs, multi-file), generates a FixBlueprint
that code-architect can implement or Azrael can review.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("GAIA.CodeMind.Analyzer")


# ── Fix Complexity ───────────────────────────────────────────────────────

class FixComplexity:
    """Classification of fix difficulty — determines routing."""
    TRIVIAL = "trivial"      # Lint, whitespace, unused import — CodeMind auto-fixes
    SIMPLE = "simple"        # Single-file logic fix — CodeMind proposes, validates
    MODERATE = "moderate"    # Multi-file coordinated change — blueprint required
    COMPLEX = "complex"      # Architectural change — Azrael review required


@dataclass
class FixTarget:
    """A single file that needs modification as part of a fix."""
    file_path: str
    change_description: str
    line_range: Optional[str] = None  # e.g., "38-49"
    priority: int = 1  # lower = fix first


@dataclass
class FixBlueprint:
    """Structured proposal for a multi-file fix.

    Generated by the ANALYZE stage when a detection is too complex
    for a single-file CodeMind fix. Can be consumed by:
    - code-architect adapter (for automated implementation)
    - Azrael (for review and manual implementation)
    - CodeMind (for staged, file-by-file application)
    """
    blueprint_id: str = ""
    title: str = ""
    root_cause: str = ""
    symptom: str = ""
    complexity: str = FixComplexity.SIMPLE
    targets: List[Dict[str, Any]] = field(default_factory=list)
    validation_steps: List[str] = field(default_factory=list)
    rollback_notes: str = ""
    requires_restart: List[str] = field(default_factory=list)
    requires_approval: bool = False
    created_at: str = ""
    source_detection: Optional[Dict[str, Any]] = None

    def to_dict(self) -> dict:
        return asdict(self)

    def to_prompt(self) -> str:
        """Format as a prompt for the code-architect adapter."""
        targets_text = "\n".join(
            f"  {i+1}. {t['file_path']}: {t['change_description']}"
            + (f" (lines {t['line_range']})" if t.get('line_range') else "")
            for i, t in enumerate(self.targets)
        )
        validation_text = "\n".join(f"  - {v}" for v in self.validation_steps)
        return f"""FIX BLUEPRINT: {self.title}

ROOT CAUSE: {self.root_cause}

SYMPTOM: {self.symptom}

FILES TO MODIFY:
{targets_text}

VALIDATION:
{validation_text}

ROLLBACK: {self.rollback_notes}

SERVICES TO RESTART: {', '.join(self.requires_restart) if self.requires_restart else 'none'}
"""


# ── Analysis Functions ───────────────────────────────────────────────────

def classify_complexity(detection: Dict[str, Any]) -> str:
    """Determine fix complexity from a detection entry."""
    issue_type = detection.get("issue_type", "")
    description = detection.get("description", "")
    file_path = detection.get("file_path", "")

    # Trivial: lint/style errors
    trivial_types = {"lint_error", "style_error", "whitespace", "unused_import"}
    if issue_type in trivial_types:
        return FixComplexity.TRIVIAL

    # Simple: single-file errors with clear fix
    simple_types = {"import_error", "syntax_error", "type_error", "undefined_name"}
    if issue_type in simple_types:
        return FixComplexity.SIMPLE

    # Check for multi-file indicators
    multi_file_keywords = [
        "across services", "inter-service", "multiple files",
        "propagat", "cascade", "both", "and also",
    ]
    desc_lower = description.lower()
    if any(kw in desc_lower for kw in multi_file_keywords):
        return FixComplexity.MODERATE

    # Behavioral issues are at least moderate
    behavioral_types = {"response_drift", "behavioral_bug", "regression", "timing_error"}
    if issue_type in behavioral_types:
        return FixComplexity.MODERATE

    # Default to simple
    return FixComplexity.SIMPLE


def build_analysis_prompt(detection: Dict[str, Any], related_files: List[str] = None) -> str:
    """Build an LLM prompt for root cause analysis.

    This prompt is sent to the code-architect adapter to analyze a behavioral
    bug and propose a fix blueprint.
    """
    files_section = ""
    if related_files:
        files_section = "\n\nRELATED FILES (may contain root cause):\n"
        for fp in related_files:
            try:
                content = Path(fp).read_text(encoding="utf-8")
                if len(content) > 5000:
                    content = content[:5000] + "\n... (truncated)"
                files_section += f"\n--- {fp} ---\n{content}\n"
            except OSError:
                files_section += f"\n--- {fp} --- (could not read)\n"

    return f"""You are CodeMind, GAIA's code self-improvement layer performing root cause analysis.

DETECTION:
  Source: {detection.get('source', 'unknown')}
  Type: {detection.get('issue_type', 'unknown')}
  File: {detection.get('file_path', 'unknown')}
  Description: {detection.get('description', '')}
  Severity: {detection.get('severity', 'unknown')}

{files_section}

TASK: Analyze this detection and produce a fix blueprint in JSON format:
{{
    "title": "Brief title for the fix",
    "root_cause": "What is actually causing this issue",
    "complexity": "trivial|simple|moderate|complex",
    "targets": [
        {{
            "file_path": "path/to/file.py",
            "change_description": "What needs to change in this file",
            "line_range": "optional: start-end lines",
            "priority": 1
        }}
    ],
    "validation_steps": ["How to verify the fix works"],
    "requires_restart": ["list of service containers to restart"],
    "rollback_notes": "How to undo if it breaks"
}}

If you cannot determine the root cause, respond with:
{{"title": "NEEDS_INVESTIGATION", "root_cause": "reason"}}

Respond with ONLY the JSON. No explanation."""


def parse_analysis_response(response: str) -> Optional[FixBlueprint]:
    """Parse the LLM's analysis response into a FixBlueprint."""
    # Strip markdown code fences
    text = response.strip()
    if text.startswith("```"):
        lines = text.split("\n")
        lines = [l for l in lines if not l.strip().startswith("```")]
        text = "\n".join(lines)

    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        logger.warning("CodeMind Analyzer: could not parse LLM response as JSON")
        return None

    if data.get("title") == "NEEDS_INVESTIGATION":
        logger.info("CodeMind Analyzer: LLM needs more context — %s", data.get("root_cause"))
        return None

    now = datetime.now(timezone.utc)
    blueprint = FixBlueprint(
        blueprint_id=f"fb-{now.strftime('%Y%m%d-%H%M%S')}",
        title=data.get("title", "Untitled fix"),
        root_cause=data.get("root_cause", ""),
        complexity=data.get("complexity", FixComplexity.SIMPLE),
        targets=[
            {
                "file_path": t.get("file_path", ""),
                "change_description": t.get("change_description", ""),
                "line_range": t.get("line_range"),
                "priority": t.get("priority", 1),
            }
            for t in data.get("targets", [])
        ],
        validation_steps=data.get("validation_steps", []),
        rollback_notes=data.get("rollback_notes", ""),
        requires_restart=data.get("requires_restart", []),
        requires_approval=data.get("complexity") in (FixComplexity.MODERATE, FixComplexity.COMPLEX),
        created_at=now.isoformat(),
    )
    return blueprint


# ── Blueprint Storage ────────────────────────────────────────────────────

BLUEPRINT_QUEUE_PATH = os.environ.get(
    "CODEMIND_BLUEPRINT_QUEUE",
    "/shared/codemind/blueprint_queue.jsonl",
)


def save_blueprint(blueprint: FixBlueprint, path: str = BLUEPRINT_QUEUE_PATH) -> None:
    """Save a fix blueprint to the queue for review/implementation."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "a", encoding="utf-8") as f:
        f.write(json.dumps(blueprint.to_dict(), default=str) + "\n")
    logger.info("Fix blueprint saved: %s — %s", blueprint.blueprint_id, blueprint.title)


def read_blueprints(path: str = BLUEPRINT_QUEUE_PATH, limit: int = 20) -> List[Dict[str, Any]]:
    """Read pending fix blueprints."""
    p = Path(path)
    if not p.exists():
        return []
    entries = []
    try:
        with open(p, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        entries.append(json.loads(line))
                    except json.JSONDecodeError:
                        continue
    except OSError:
        return []
    return entries[:limit]


# ── File Tracing ─────────────────────────────────────────────────────────

# Map of symptom keywords to likely related file paths (GAIA-specific)
TRACE_MAP = {
    "time": [
        "candidates/gaia-core/gaia_core/utils/prompt_builder.py",
        "candidates/gaia-common/gaia_common/engine/core.py",
        "candidates/gaia-common/gaia_common/utils/world_state.py",
    ],
    "discord": [
        "candidates/gaia-web/gaia_web/discord_interface.py",
        "candidates/gaia-web/gaia_web/queue/message_queue.py",
    ],
    "prompt": [
        "candidates/gaia-core/gaia_core/utils/prompt_builder.py",
        "candidates/gaia-core/gaia_core/cognition/agent_core.py",
    ],
    "model": [
        "candidates/gaia-core/gaia_core/models/vllm_remote_model.py",
        "candidates/gaia-core/gaia_core/models/_model_pool_impl.py",
    ],
    "sleep": [
        "candidates/gaia-core/gaia_core/cognition/sleep_task_scheduler.py",
    ],
    "security": [
        "candidates/gaia-web/gaia_web/security/scanner.py",
        "candidates/gaia-web/gaia_web/security/middleware.py",
    ],
    "immune": [
        "candidates/gaia-common/gaia_common/utils/immune_system.py",
        "candidates/gaia-doctor/doctor.py",
    ],
    "cache": [
        "candidates/gaia-common/gaia_common/engine/core.py",
    ],
    "lora": [
        "candidates/gaia-core/gaia_core/models/vllm_remote_model.py",
        "candidates/gaia-core/gaia_core/models/_model_pool_impl.py",
    ],
    "mcp": [
        "candidates/gaia-mcp/gaia_mcp/tools.py",
        "candidates/gaia-mcp/gaia_mcp/jsonrpc.py",
    ],
    "file": [
        "candidates/gaia-mcp/gaia_mcp/tools.py",
        "candidates/gaia-web/gaia_web/routes/files.py",
        "candidates/gaia-web/gaia_web/routes/chat.py",
    ],
    "attachment": [
        "candidates/gaia-mcp/gaia_mcp/tools.py",
        "candidates/gaia-web/gaia_web/routes/chat.py",
        "candidates/gaia-web/static/app.js",
        "candidates/gaia-common/gaia_common/protocols/cognition_packet.py",
    ],
    "upload": [
        "candidates/gaia-web/gaia_web/routes/chat.py",
        "candidates/gaia-web/gaia_web/routes/files.py",
        "candidates/gaia-web/static/app.js",
    ],
    "route": [
        "candidates/gaia-web/gaia_web/routes/system.py",
        "candidates/gaia-web/gaia_web/routes/hooks.py",
        "candidates/gaia-web/gaia_web/routes/chat.py",
    ],
    "dashboard": [
        "candidates/gaia-web/static/app.js",
        "candidates/gaia-web/static/index.html",
        "candidates/gaia-web/static/style.css",
    ],
    "training": [
        "candidates/gaia-study/scripts/build_curriculum.py",
        "candidates/gaia-core/gaia_core/cognition/observer_scorer.py",
    ],
}


def trace_related_files(detection: Dict[str, Any]) -> List[str]:
    """Given a detection, find likely related source files for root cause analysis.

    Uses keyword matching against the TRACE_MAP and the detection's file_path
    to find files that might contain the root cause.
    """
    related = set()
    description = detection.get("description", "").lower()
    issue_type = detection.get("issue_type", "").lower()
    file_path = detection.get("file_path", "")

    # Add the detection's own file
    if file_path and os.path.isfile(file_path):
        related.add(file_path)

    # Keyword-based tracing
    search_text = f"{description} {issue_type}"
    for keyword, files in TRACE_MAP.items():
        if keyword in search_text:
            for fp in files:
                if os.path.isfile(fp):
                    related.add(fp)

    return sorted(related)[:6]  # Cap at 6 files to stay within token budget
