"""CodeMind dashboard proxy routes.

Exposes CodeMind status, changelog, and trigger endpoints for Mission Control.
"""

import json
import logging
import os
from pathlib import Path

from fastapi import APIRouter, Request

logger = logging.getLogger("GAIA.Web.CodeMind")

router = APIRouter()

# CodeMind reads shared files directly — no proxy needed for status/changelog
CODEMIND_CHANGELOG_PATH = os.environ.get(
    "CODEMIND_CHANGELOG_PATH",
    "/shared/codemind/changelog.jsonl",
)
CODEMIND_DETECT_QUEUE = os.environ.get(
    "CODEMIND_DETECT_QUEUE",
    "/shared/codemind/detect_queue.jsonl",
)
CORE_URL = os.getenv("CORE_ENDPOINT", "http://gaia-core:6415")


@router.get("/status")
async def codemind_status():
    """Return CodeMind engine status from shared state."""
    try:
        from gaia_common.utils.codemind_engine import CodeMindEngine, _load_config
        # Load config from constants if available
        constants_path = os.environ.get(
            "GAIA_CONSTANTS_PATH",
            "/gaia-common/gaia_common/constants/gaia_constants.json",
        )
        constants = {}
        try:
            with open(constants_path, "r") as f:
                constants = json.load(f)
        except Exception:
            pass
        engine = CodeMindEngine(constants)
        return engine.status()
    except ImportError:
        return {"state": "UNAVAILABLE", "error": "codemind_engine not available"}
    except Exception as e:
        return {"state": "ERROR", "error": str(e)}


@router.get("/changelog")
async def codemind_changelog(limit: int = 20, offset: int = 0):
    """Return recent CodeMind changelog entries."""
    try:
        from gaia_common.utils.codemind_changelog import read_entries, summary
        entries = read_entries(CODEMIND_CHANGELOG_PATH, limit=limit, offset=offset)
        stats = summary(CODEMIND_CHANGELOG_PATH)
        return {
            "entries": entries,
            "total": stats.get("total", 0),
            "outcomes": stats.get("outcomes", {}),
        }
    except ImportError:
        return {"entries": [], "error": "codemind_changelog not available"}
    except Exception as e:
        return {"entries": [], "error": str(e)}


@router.get("/queue")
async def codemind_queue():
    """Return pending detection queue size and entries."""
    try:
        from gaia_common.utils.codemind_detector import read_detections, queue_size
        size = queue_size(CODEMIND_DETECT_QUEUE)
        entries = read_detections(CODEMIND_DETECT_QUEUE, limit=20)
        return {"size": size, "entries": entries}
    except ImportError:
        return {"size": 0, "error": "codemind_detector not available"}
    except Exception as e:
        return {"size": 0, "error": str(e)}


@router.get("/blueprints")
async def codemind_blueprints():
    """Return pending fix blueprints generated by the analyzer."""
    try:
        from gaia_common.utils.codemind_analyzer import read_blueprints
        blueprints = read_blueprints(limit=20)
        return {"blueprints": blueprints, "count": len(blueprints)}
    except ImportError:
        return {"blueprints": [], "error": "codemind_analyzer not available"}
    except Exception as e:
        return {"blueprints": [], "error": str(e)}


@router.get("/heartbeat")
async def heartbeat_status():
    """Return heartbeat time check status."""
    try:
        from gaia_common.utils.heartbeat_time_check import read_state
        return read_state()
    except ImportError:
        return {"current": None, "error": "heartbeat_time_check not available"}
    except Exception as e:
        return {"current": None, "error": str(e)}


@router.post("/trigger")
async def codemind_trigger(request: Request):
    """Trigger a CodeMind cycle via gaia-core."""
    try:
        import httpx
        body = {}
        try:
            body = await request.json()
        except Exception:
            pass
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(
                f"{CORE_URL}/api/codemind/trigger",
                json=body,
            )
            return resp.json()
    except Exception as e:
        logger.warning("CodeMind trigger failed: %s", e)
        return {"ok": False, "error": str(e)}
