"""
Curriculum review queue routes for Mission Control dashboard.

Provides endpoints for reviewing, approving, and rejecting curriculum
candidate files generated by the Open Knowledge Ingestion system.
"""

import json
import logging
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

logger = logging.getLogger("GAIA.Web.Curriculum")

router = APIRouter()

# Paths — inside the container, /shared is the shared volume
CANDIDATES_DIR = Path(os.getenv("CURRICULUM_CANDIDATES_DIR", "/shared/knowledge/candidates"))
APPROVED_DIR = Path(os.getenv("CURRICULUM_APPROVED_DIR", "/shared/knowledge/approved"))
REJECTED_DIR = Path(os.getenv("CURRICULUM_REJECTED_DIR", "/shared/knowledge/rejected"))
TRAIN_JSONL = Path(os.getenv("CURRICULUM_TRAIN_JSONL", "/knowledge/curricula/self-model/train.jsonl"))


class ApproveRequest(BaseModel):
    approve_all: bool = False
    pair_indices: Optional[list[int]] = None


def _ensure_dirs():
    """Ensure output directories exist."""
    for d in (APPROVED_DIR, REJECTED_DIR):
        d.mkdir(parents=True, exist_ok=True)
    TRAIN_JSONL.parent.mkdir(parents=True, exist_ok=True)


def _parse_candidate(filepath: Path) -> dict:
    """Parse a candidate JSON file and return metadata."""
    try:
        with filepath.open() as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.warning("Failed to parse candidate %s: %s", filepath.name, e)
        return None

    # Support both {"pairs": [...]} and bare list formats
    if isinstance(data, list):
        pairs = data
    elif isinstance(data, dict):
        pairs = data.get("pairs", data.get("data", []))
    else:
        return None

    # Extract metadata
    course = ""
    if isinstance(data, dict):
        course = data.get("course", data.get("source", ""))

    stat = filepath.stat()
    return {
        "filename": filepath.name,
        "course": course,
        "pair_count": len(pairs),
        "timestamp": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
        "status": "pending",
    }


def _load_pairs(filepath: Path) -> list[dict]:
    """Load training pairs from a candidate file."""
    try:
        with filepath.open() as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return []

    if isinstance(data, list):
        return data
    elif isinstance(data, dict):
        return data.get("pairs", data.get("data", []))
    return []


@router.get("/candidates")
async def list_candidates():
    """List pending candidate files."""
    if not CANDIDATES_DIR.exists():
        return []

    results = []
    for fp in sorted(CANDIDATES_DIR.iterdir()):
        if fp.suffix == ".json" and fp.is_file():
            info = _parse_candidate(fp)
            if info:
                results.append(info)

    return results


@router.get("/candidates/{filename}")
async def get_candidate(filename: str):
    """Return full pair list from a candidate file."""
    # Sanitize filename — no path traversal
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    filepath = CANDIDATES_DIR / filename
    if not filepath.exists() or not filepath.is_file():
        raise HTTPException(status_code=404, detail="Candidate not found")

    pairs = _load_pairs(filepath)
    info = _parse_candidate(filepath)
    if info:
        info["pairs"] = pairs
    return info or {"filename": filename, "pairs": pairs}


@router.post("/candidates/{filename}/approve")
async def approve_candidate(filename: str, body: ApproveRequest):
    """Approve pairs from a candidate file and append to train.jsonl."""
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    filepath = CANDIDATES_DIR / filename
    if not filepath.exists() or not filepath.is_file():
        raise HTTPException(status_code=404, detail="Candidate not found")

    _ensure_dirs()
    pairs = _load_pairs(filepath)

    if body.approve_all:
        approved_pairs = pairs
    elif body.pair_indices:
        approved_pairs = [pairs[i] for i in body.pair_indices if 0 <= i < len(pairs)]
    else:
        raise HTTPException(status_code=400, detail="Must specify approve_all or pair_indices")

    # Append approved pairs to train.jsonl
    if approved_pairs:
        with TRAIN_JSONL.open("a") as f:
            for pair in approved_pairs:
                f.write(json.dumps(pair, ensure_ascii=False) + "\n")
        logger.info("Appended %d pairs from %s to %s", len(approved_pairs), filename, TRAIN_JSONL)

    # Move candidate to approved directory
    shutil.move(str(filepath), str(APPROVED_DIR / filename))
    logger.info("Approved candidate %s (%d/%d pairs)", filename, len(approved_pairs), len(pairs))

    return {
        "ok": True,
        "approved": len(approved_pairs),
        "total": len(pairs),
        "destination": str(TRAIN_JSONL),
    }


@router.post("/candidates/{filename}/reject")
async def reject_candidate(filename: str):
    """Reject a candidate file — move to rejected directory."""
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    filepath = CANDIDATES_DIR / filename
    if not filepath.exists() or not filepath.is_file():
        raise HTTPException(status_code=404, detail="Candidate not found")

    _ensure_dirs()
    shutil.move(str(filepath), str(REJECTED_DIR / filename))
    logger.info("Rejected candidate %s", filename)

    return {"ok": True, "filename": filename}


@router.get("/stats")
async def curriculum_stats():
    """Summary counts for curriculum queue."""
    def _count_json(d: Path) -> int:
        if not d.exists():
            return 0
        return sum(1 for f in d.iterdir() if f.suffix == ".json" and f.is_file())

    pending = _count_json(CANDIDATES_DIR)
    approved = _count_json(APPROVED_DIR)
    rejected = _count_json(REJECTED_DIR)

    # Count total training pairs in train.jsonl
    train_pairs = 0
    if TRAIN_JSONL.exists():
        with TRAIN_JSONL.open() as f:
            for _ in f:
                train_pairs += 1

    return {
        "pending": pending,
        "approved": approved,
        "rejected": rejected,
        "train_pairs": train_pairs,
    }
