"""LLM-driven playbook body generator for self-improving skills (99z).

5qy Phase 1 shipped the substrate: a failure-pattern accumulator + a
deterministic SKILL.md drafter with a pluggable `body_generator` hook.
Phase 2 (this module) wires the LLM call: given a failure pattern +
sample failed queries, ask Prime to draft a playbook for handling them.

The LLM hook is injected via `make_llm_body_generator()` — returns a
function compatible with skill_creator.draft_skill_from_failures'
body_generator parameter. Failure modes (Prime unavailable, consistency
audit rejects the output, malformed response) all fall through to the
deterministic TODO template, so the sleep-cycle hook never blocks on
LLM outage.

Uses the creative_generation route (45i) so the body generation gets
the same KG-recency grounding + consistency-detector + re-roll
protections any other creative output goes through.
"""

from __future__ import annotations

import logging
from typing import Callable, Optional

logger = logging.getLogger("GAIA.SkillLLMBody")


# Persona prompt for the playbook-author role. Kept terse — the
# downstream creative_generation route prepends its own grounding
# instructions; this just frames the task.
_SYSTEM_PROMPT = (
    "You are GAIA, drafting a playbook for handling a recurring "
    "failure pattern in your skills system. You will see a trigger "
    "pattern key and N sample queries that all failed under the "
    "current behavior.\n\n"
    "Write a focused, numbered playbook (3-7 steps) that would handle "
    "queries matching this pattern. Each step should be concrete and "
    "actionable: which MCP tool to call, what to extract from the "
    "result, how to respond. Avoid speculation about specific tool "
    "parameters or file paths unless they appear in the failure "
    "samples. End with a single-line note on when to escalate or "
    "decline (rather than guess).\n\n"
    "Output ONLY the playbook markdown — no preamble, no closing "
    "summary, no explanation of your reasoning. Start with '1.' and "
    "stop after the last step or escalation note."
)


def _build_user_prompt(pattern: str, failures: list[dict]) -> str:
    """Compose the prompt body for the LLM call."""
    intent_part = pattern.split(":", 1)[0]
    query_part = pattern.split(":", 1)[1] if ":" in pattern else pattern

    lines = [
        f"**Pattern key**: `{pattern}`",
        f"**Intent**: {intent_part}",
        f"**Query topic**: {query_part}",
        "",
        f"**Failure samples** (n={len(failures)}):",
    ]
    for f in failures[:10]:
        q = (f.get("query") or "").strip()
        if len(q) > 200:
            q = q[:200] + "..."
        intent = f.get("intent") or "unknown"
        lines.append(f"  - [{intent}] {q}")
    if len(failures) > 10:
        lines.append(f"  - ... ({len(failures) - 10} more)")
    lines.extend([
        "",
        "Write the playbook below.",
    ])
    return "\n".join(lines)


def _wrap_playbook(pattern: str, failures: list[dict], playbook: str,
                   *, description: str = "") -> str:
    """Wrap the LLM-generated playbook into the full SKILL.md body.

    Mirrors the structure of skill_creator._default_body_generator so
    the result has the same outline (pattern, failure samples,
    playbook, notes) — just with LLM-authored steps replacing the
    TODO placeholder.
    """
    from gaia_common.utils.skill_creator import _format_failure_block

    return f"""# LLM-drafted skill from {len(failures)} failures

**Trigger pattern**: `{pattern}`

**Description**: {description or "Auto-generated handler for repeated failures."}

**Status**: draft — playbook generated by Prime; review before promoting
to a routable skill. Increment frontmatter `version` and flip `status`
to `active` when ready.

## Recent failure samples

{_format_failure_block(failures)}

## Playbook steps

{playbook.strip()}

## Notes

- This file lives under `/knowledge/skills/auto/` — auto-generated
  skills are kept separate from hand-written ones.
- The playbook above was drafted by Prime via the creative_generation
  route, with consistency-audit + KG-recency grounding applied.
- Review for correctness before relying on it — delete the directory
  if the pattern isn't worth a dedicated skill.
"""


def make_llm_body_generator(
    *,
    endpoint: str = "http://gaia-prime:7777",
    model: str = "/models/prime",
    max_tokens: int = 600,
    temperature: float = 0.6,
    max_rerolls: int = 1,
) -> Callable[[str, list[dict]], str]:
    """Return a body_generator callable for skill_creator.draft_skill_from_failures.

    The returned function calls generate_creative_grounded (45i) against
    the configured endpoint and returns the LLM-authored body. On any
    failure (transport error, consistency audit rejects the output,
    empty response) it falls back to skill_creator's deterministic
    template so the calling sleep-cycle hook never breaks.
    """
    def _generator(pattern: str, failures: list[dict]) -> str:
        from gaia_core.cognition.creative_generation import (
            generate_creative_grounded,
        )
        from gaia_common.utils.skill_creator import _default_body_generator

        intent_part = pattern.split(":", 1)[0]
        query_part = pattern.split(":", 1)[1] if ":" in pattern else pattern
        description = (
            f"LLM-drafted handler for failed '{intent_part}' queries about: "
            f"{query_part}"
        )

        user_prompt = _build_user_prompt(pattern, failures)

        # consistency_source_text: the failure samples themselves —
        # gives the consistency detector something to anchor against
        # if the LLM invents an entity (e.g. fake tool name).
        source_text = "\n".join(
            (f.get("query") or "") for f in failures
        )

        try:
            result = generate_creative_grounded(
                system_prompt=_SYSTEM_PROMPT,
                user_prompt=user_prompt,
                consistency_source_text=source_text,
                grounding_evidence="",
                endpoint=endpoint,
                model=model,
                max_tokens=max_tokens,
                temperature=temperature,
                repetition_penalty=1.15,
                max_rerolls=max_rerolls,
                enable_kg_grounding=True,
            )
        except Exception as e:
            logger.warning("LLM body generation raised; falling back: %s", e)
            return _default_body_generator(pattern, failures, description=description)

        if result.error or not (result.text or "").strip():
            logger.info(
                "LLM body generation failed (%s); falling back to deterministic body",
                result.error or "empty text",
            )
            return _default_body_generator(pattern, failures, description=description)

        playbook = result.text.strip()
        # Strip any leaked think-tag content (defensive — Prime sometimes
        # emits <think>...</think> in the body).
        import re as _re
        playbook = _re.sub(r"<think>.*?</think>", "", playbook, flags=_re.DOTALL).strip()

        if not playbook:
            return _default_body_generator(pattern, failures, description=description)

        if not result.consistency_clean and result.fabrications_found:
            logger.info(
                "LLM playbook had %d unsourced terms after %d rerolls — accepting "
                "anyway (auto-skill is human-reviewed): %s",
                len(result.fabrications_found), result.rerolls,
                result.fabrications_found[:3],
            )

        return _wrap_playbook(pattern, failures, playbook, description=description)

    return _generator


# ── Sleep-cycle entry point ──────────────────────────────────────────


def run_skill_creator_cycle(
    *,
    threshold: int = 3,
    window_hours: float = 7 * 24,
    log_path: Optional[str] = None,
    output_dir=None,
    use_llm: bool = True,
    llm_endpoint: str = "http://gaia-prime:7777",
    llm_model: str = "/models/prime",
    reload_url: Optional[str] = None,
) -> dict:
    """Self-improving skills sleep-cycle entry point.

    Runs maybe_draft_skills with the LLM body generator (or
    deterministic if use_llm=False), then optionally calls the
    SkillGateway reload endpoint so newly-drafted skills enter the
    registry on the next reload.

    Returns a summary dict with the per-pattern results + reload
    outcome. Designed to be called from a SleepTask handler.

    log_path: optional explicit failure-log path. When None, the
    underlying skill_failures module reads from GAIA_SKILL_FAILURE_LOG
    env var at call time (re-read each call so a process restart picks
    up env changes).
    """
    import os
    from gaia_common.utils.skill_creator import maybe_draft_skills

    body_gen = None
    if use_llm:
        body_gen = make_llm_body_generator(
            endpoint=llm_endpoint, model=llm_model,
        )

    # Re-resolve the failure log from the env var if not explicit —
    # the underlying module caches DEFAULT_LOG_PATH at import, but
    # this entry point is meant for sleep-cycle reuse where the env
    # may have changed (e.g., test fixtures via monkeypatch).
    effective_log_path = log_path or os.environ.get("GAIA_SKILL_FAILURE_LOG")

    drafts = maybe_draft_skills(
        threshold=threshold,
        window_hours=window_hours,
        log_path=effective_log_path,
        output_dir=output_dir,
        body_generator=body_gen,
        clear_after_draft=True,
    )

    drafted_skills = [d for d in drafts if d.get("ok")]
    if not drafted_skills:
        logger.debug("skill_creator_cycle: no patterns above threshold")
        return {
            "ok": True,
            "drafted": 0,
            "drafts": drafts,
            "reloaded": False,
        }

    reloaded = False
    reload_error = None
    if reload_url:
        try:
            import urllib.request
            req = urllib.request.Request(
                reload_url,
                data=b"{}",
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                _body = resp.read()
            reloaded = True
        except Exception as e:
            reload_error = str(e)
            logger.warning("skill_creator_cycle: reload trigger failed: %s", e)

    logger.info(
        "skill_creator_cycle: drafted %d skills (reload=%s)",
        len(drafted_skills), "ok" if reloaded else (reload_error or "skipped"),
    )
    return {
        "ok": True,
        "drafted": len(drafted_skills),
        "drafts": drafts,
        "reloaded": reloaded,
        "reload_error": reload_error,
    }
